name: Obfuscate worker.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  obfuscate:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js (for obfuscation)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install JavaScript obfuscation tool
      - name: Install JavaScript obfuscator
        run: npm install javascript-obfuscator

      # Backup the worker.js file
      - name: Backup worker.js
        run: cp src/worker.js src/worker.js.bak

      # Obfuscate the worker.js file
      - name: Obfuscate worker.js
        run: npx javascript-obfuscator src/worker.js --output src/worker.js

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/worker.js
          git add src/worker.js.bak
          git commit -m "Obfuscated worker.js and backed up original as .bak"
          git push
